name: gnostr-docker

on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        tag: ["latest", "slim-bullseye", "slim-bookworm"]

    container: rust:${{ matrix.tag }}

    steps:
      ## notice: this is a pre checkout step
      ## notice: additional operations can be done prior to checkout
      ## - run: apk update && apk add bash cmake git python3 && python3 -m ensurepip
      - run: apt-get update && apt-get install build-essential cmake libexpat1-dev libcurl4-openssl-dev libssl-dev git make pkg-config python3 python-is-python3 sudo tcl zlib1g-dev -y
      - run: printenv
      - name: checkout@v3 fetch-depth submodules set-safe-dir true
        uses: actions/checkout@v3
        with:
          fetch-depth: '100'
          submodules: 'true'
          set-safe-directory: 'true'
      ## notice: these are post checkout steps
      ## - run: apk update && apk add autoconf automake build-base openssl-dev libtool make
      - run: touch ~/GITHUB_TOKEN.txt
      - run: git config --global --add safe.directory /__w/gnostr/gnostr || true
      - run: make detect
      - run: make
      - run: make gnostr-legit
      - run: make bins
      - run: make      tui
      - run: make          gnostr-git
      - run: make                     gnostr-all
      - run: make                                gnostr-install
      - run: make                                               all
      - run: make                                                   install
      - run: gnostr --sec $(gnostr-sha256) --content "$(gnostr-git show HEAD)" | gnostr-post-event wss://relay.damus.io
      - run: make bins-test-fetch-by-id
